baseURL = "https://oscarforner.com/"
languageCode = "en-us"
title = "Oscar Forner"
theme = "simple-hugo"

# Menu definition
[menu]
  # Top (main) menu
  [[menu.main]]
    weight = 1
    URL = "whoami"
    Name = "$(whoami)"
  [[menu.main]]
    weight = 2
    URL = "projects"
    Name = "Projects"
  [[menu.main]]
    weight = 3
    URL = "resume"
    Name = "Resume"

# Site parameters
[params]

